wandb_version: 1

gamma:
  value: 0.5791178709636672
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 7
learning_rate:
  value: 0.006509969730268811
max_depth:
  value: 6
min_child_weight:
  value: 9
n_estimators:
  value: 302
reg_alpha:
  value: 5
reg_lambda:
  value: 5
scaler:
  value: standard
variance_threshold:
  value: 0.01772794983028029
