data_path:
    github_csv: "https://github.com/carlosjara/MCD_FAII/blob/main/FAII/Talleres/Taller_Practico/data/df_train.csv?raw=true"
    github_parquet: "https://github.com/carlosjara/MCD_FAII/blob/main/FAII/Talleres/Taller_Practico/data/df_train.parquet?raw=true"
    github_parquet_test: "https://github.com/carlosjara/MCD_FAII/blob/main/FAII/Talleres/Taller_Practico/data/df_test.parquet?raw=true"
    stage_processed : 'data/stg'
# Configuración de la aplicación
app_config:
  nombre: Taller1
  version: 1.0
  autores: YasminGarcia/CarlosJaramillo
  descripcion: Taller 1


# Configuración de la búsqueda de hiperparámetros
hyperparameter_search:
  name: XGBOOST 
  method: bayes
  metric:
    name: mean_average_precision_val
    goal: maximize
  parameters:
    n_estimators:
      min: 200
      max: 500
    learning_rate:
      min: 1e-4
      max: 1e-2
    gamma:
      min: 0.1
      max: 5.0
    min_child_weight:
      min: 4
      max: 12
    max_depth:
      min: 6
      max: 10
    reg_alpha:
      min: 4
      max: 7
    reg_lambda:
      min: 4
      max: 7
    imputer_strategy:
        min: 0.0
        max: 1.0
    knn_imputer:
      min: 0.0
      max: 1.0
    knn_imputer_k:
      min: 3
      max: 10
    variance_threshold:
      min: 0.0
      max: 0.1
    scaler_choice:
        min: 0.0
        max: 1.0


#Este es ejemplo de YAML
# Configuración del servidor
#server_config:
#  puerto: 8080
#  host: localhost
#  debug: true

# Configuración de la base de datos
#database_config:
#  tipo: MySQL
#  nombre: mi_base_de_datos
#  usuario: usuario_db
#  contraseña: secreto
#  parametros:
#    timeout: 60
#    max_conexiones: 100

# Configuración de la interfaz de usuario
#ui_config:
#  tema: oscuro
#  idioma: español
#  colores:
#    fondo: '#333333'
#    texto: '#FFFFFF'
#  tamaño_fuente: 14
