wandb_version: 1

gamma:
  value: 3.532305775010586
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 12
learning_rate:
  value: 0.0008849365869864975
max_depth:
  value: 8
min_child_weight:
  value: 9
n_estimators:
  value: 360
reg_alpha:
  value: 6
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.014558895485788438
