wandb_version: 1

gamma:
  value: 1.6746096557305554
imputer:
  value: simple
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 3
learning_rate:
  value: 0.00980814251103933
max_depth:
  value: 6
min_child_weight:
  value: 11
n_estimators:
  value: 429
reg_alpha:
  value: 7
reg_lambda:
  value: 6
scaler:
  value: robust
variance_threshold:
  value: 0.08615618083170641
