wandb_version: 1

gamma:
  value: 1.2138209015819934
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 7
learning_rate:
  value: 0.002908663288946496
max_depth:
  value: 9
min_child_weight:
  value: 9
n_estimators:
  value: 257
reg_alpha:
  value: 5
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.04817270734880529
