wandb_version: 1

gamma:
  value: 1.9083229660582597
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 6
learning_rate:
  value: 0.0016486171412801532
max_depth:
  value: 10
min_child_weight:
  value: 8
n_estimators:
  value: 279
reg_alpha:
  value: 5
reg_lambda:
  value: 7
scaler:
  value: robust
variance_threshold:
  value: 0.08972290189175815
