wandb_version: 1

gamma:
  value: 3.1738951802075497
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 5
learning_rate:
  value: 0.004396729475729492
max_depth:
  value: 8
min_child_weight:
  value: 11
n_estimators:
  value: 299
reg_alpha:
  value: 5
reg_lambda:
  value: 4
scaler:
  value: robust
variance_threshold:
  value: 0.09549942217899753
