wandb_version: 1

gamma:
  value: 3.9705834127904
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 3
learning_rate:
  value: 0.004074340820500647
max_depth:
  value: 6
min_child_weight:
  value: 5
n_estimators:
  value: 357
reg_alpha:
  value: 5
reg_lambda:
  value: 6
scaler:
  value: standard
variance_threshold:
  value: 0.04914328658895887
