wandb_version: 1

gamma:
  value: 4.450847887215298
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 10
learning_rate:
  value: 0.009304724931550688
max_depth:
  value: 10
min_child_weight:
  value: 6
n_estimators:
  value: 473
reg_alpha:
  value: 6
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.04813700003294763
