wandb_version: 1

gamma:
  value: 4.407447570943698
imputer:
  value: simple
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 6
learning_rate:
  value: 0.001685098809016937
max_depth:
  value: 6
min_child_weight:
  value: 6
n_estimators:
  value: 492
reg_alpha:
  value: 4
reg_lambda:
  value: 5
scaler:
  value: standard
variance_threshold:
  value: 0.0025850219488734007
