wandb_version: 1

gamma:
  value: 1.889311004269533
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 8
learning_rate:
  value: 0.004728252739326501
max_depth:
  value: 6
min_child_weight:
  value: 8
n_estimators:
  value: 438
reg_alpha:
  value: 5
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.0016896318926316713
