wandb_version: 1

gamma:
  value: 1.6703114192133697
imputer:
  value: knn
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 15
learning_rate:
  value: 0.0050934237219610705
max_depth:
  value: 8
min_child_weight:
  value: 9
n_estimators:
  value: 365
reg_alpha:
  value: 6
reg_lambda:
  value: 4
scaler:
  value: robust
variance_threshold:
  value: 0.003101838470157547
