wandb_version: 1

gamma:
  value: 2.1295057728536135
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 13
learning_rate:
  value: 0.000276868354799517
max_depth:
  value: 7
min_child_weight:
  value: 8
n_estimators:
  value: 403
reg_alpha:
  value: 7
reg_lambda:
  value: 4
scaler:
  value: robust
variance_threshold:
  value: 0.02137944255230833
