wandb_version: 1

gamma:
  value: 3.3435676262777343
imputer:
  value: knn
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 13
learning_rate:
  value: 0.0012092937972553643
max_depth:
  value: 8
min_child_weight:
  value: 7
n_estimators:
  value: 278
reg_alpha:
  value: 7
reg_lambda:
  value: 5
scaler:
  value: robust
variance_threshold:
  value: 0.08684278531217103
