wandb_version: 1

gamma:
  value: 3.328620046920448
imputer:
  value: knn
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 10
learning_rate:
  value: 0.004346831206593096
max_depth:
  value: 10
min_child_weight:
  value: 9
n_estimators:
  value: 322
reg_alpha:
  value: 7
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.049048298418489705
