wandb_version: 1

gamma:
  value: 0.12626122552260946
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 5
learning_rate:
  value: 0.001698218901998659
max_depth:
  value: 6
min_child_weight:
  value: 9
n_estimators:
  value: 466
reg_alpha:
  value: 5
reg_lambda:
  value: 5
scaler:
  value: robust
variance_threshold:
  value: 0.062355638787055835
