wandb_version: 1

gamma:
  value: 2.3047124607950993
imputer:
  value: simple
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 6
learning_rate:
  value: 0.008279206499919643
max_depth:
  value: 9
min_child_weight:
  value: 9
n_estimators:
  value: 383
reg_alpha:
  value: 5
reg_lambda:
  value: 7
scaler:
  value: standard
variance_threshold:
  value: 0.006036245578831367
