wandb_version: 1

gamma:
  value: 1.773303873998619
imputer:
  value: simple
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 11
learning_rate:
  value: 0.004989607676097556
max_depth:
  value: 7
min_child_weight:
  value: 10
n_estimators:
  value: 398
reg_alpha:
  value: 6
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.09755544435800684
