wandb_version: 1

gamma:
  value: 4.364721579072377
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 9
learning_rate:
  value: 0.007423234801737947
max_depth:
  value: 6
min_child_weight:
  value: 10
n_estimators:
  value: 273
reg_alpha:
  value: 4
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.09898891546571324
