wandb_version: 1

gamma:
  value: 4.4534393851819125
imputer:
  value: simple
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 5
learning_rate:
  value: 0.0014513411269294835
max_depth:
  value: 8
min_child_weight:
  value: 7
n_estimators:
  value: 333
reg_alpha:
  value: 6
reg_lambda:
  value: 7
scaler:
  value: robust
variance_threshold:
  value: 0.0041848432827385155
