wandb_version: 1

gamma:
  value: 0.1347841180736178
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 6
learning_rate:
  value: 0.006703142173144918
max_depth:
  value: 8
min_child_weight:
  value: 6
n_estimators:
  value: 200
reg_alpha:
  value: 7
reg_lambda:
  value: 7
scaler:
  value: robust
variance_threshold:
  value: 0.08281531260291941
