wandb_version: 1

gamma:
  value: 1.72358756470356
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 12
learning_rate:
  value: 0.000994963080858441
max_depth:
  value: 9
min_child_weight:
  value: 8
n_estimators:
  value: 323
reg_alpha:
  value: 5
reg_lambda:
  value: 5
scaler:
  value: standard
variance_threshold:
  value: 0.0217001370983695
