wandb_version: 1

gamma:
  value: 4.279554001534555
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 12
learning_rate:
  value: 0.009462826946996229
max_depth:
  value: 9
min_child_weight:
  value: 7
n_estimators:
  value: 448
reg_alpha:
  value: 4
reg_lambda:
  value: 5
scaler:
  value: standard
variance_threshold:
  value: 0.09313948038179252
