wandb_version: 1

gamma:
  value: 1.4991735545393323
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 4
learning_rate:
  value: 0.0004438400545868861
max_depth:
  value: 7
min_child_weight:
  value: 5
n_estimators:
  value: 331
reg_alpha:
  value: 4
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.08308220041262199
