wandb_version: 1

gamma:
  value: 3.4488043769780647
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 6
learning_rate:
  value: 0.009747743205158886
max_depth:
  value: 9
min_child_weight:
  value: 4
n_estimators:
  value: 493
reg_alpha:
  value: 5
reg_lambda:
  value: 7
scaler:
  value: standard
variance_threshold:
  value: 0.05451192880591387
