wandb_version: 1

gamma:
  value: 3.4719701318247456
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 15
learning_rate:
  value: 0.0074023967723341666
max_depth:
  value: 6
min_child_weight:
  value: 12
n_estimators:
  value: 302
reg_alpha:
  value: 6
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.017409049118756993
