wandb_version: 1

gamma:
  value: 3.1086575770837666
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 9
learning_rate:
  value: 0.0029100721446665557
max_depth:
  value: 9
min_child_weight:
  value: 12
n_estimators:
  value: 287
reg_alpha:
  value: 7
reg_lambda:
  value: 7
scaler:
  value: standard
variance_threshold:
  value: 0.012089528957870589
