wandb_version: 1

gamma:
  value: 1.7083626954086013
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 14
learning_rate:
  value: 0.001779513681107126
max_depth:
  value: 7
min_child_weight:
  value: 7
n_estimators:
  value: 489
reg_alpha:
  value: 5
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.0046875071383321145
