wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711585581.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.10.9
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 2.0392138098863146
imputer:
  desc: null
  value: knn
imputer_strategy:
  desc: null
  value: mean
knn_imputer_k:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.005663901632154771
max_depth:
  desc: null
  value: 9
min_child_weight:
  desc: null
  value: 4
n_estimators:
  desc: null
  value: 229
reg_alpha:
  desc: null
  value: 4
reg_lambda:
  desc: null
  value: 7
scaler:
  desc: null
  value: robust
variance_threshold:
  desc: null
  value: 0.03525448218368349
