wandb_version: 1

gamma:
  value: 1.8790065842388
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 12
learning_rate:
  value: 0.007904210347970363
max_depth:
  value: 6
min_child_weight:
  value: 12
n_estimators:
  value: 312
reg_alpha:
  value: 7
reg_lambda:
  value: 6
scaler:
  value: robust
variance_threshold:
  value: 0.00987546703796114
