wandb_version: 1

gamma:
  value: 1.5911183886350306
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 5
learning_rate:
  value: 0.002635154779168856
max_depth:
  value: 9
min_child_weight:
  value: 8
n_estimators:
  value: 489
reg_alpha:
  value: 4
reg_lambda:
  value: 6
scaler:
  value: robust
variance_threshold:
  value: 0.03339215215440744
