wandb_version: 1

gamma:
  value: 4.9870487302493505
imputer:
  value: knn
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 10
learning_rate:
  value: 0.00010177257512752964
max_depth:
  value: 6
min_child_weight:
  value: 12
n_estimators:
  value: 286
reg_alpha:
  value: 5
reg_lambda:
  value: 7
scaler:
  value: standard
variance_threshold:
  value: 0.049894433190288114
