wandb_version: 1

gamma:
  value: 1.8253347649703735
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 6
learning_rate:
  value: 0.004520915191403784
max_depth:
  value: 9
min_child_weight:
  value: 8
n_estimators:
  value: 414
reg_alpha:
  value: 6
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.02579056042390724
