wandb_version: 1

gamma:
  value: 4.754812623806893
imputer:
  value: knn
imputer_strategy:
  value: mean
knn_imputer_k:
  value: 9
learning_rate:
  value: 0.008523669564236457
max_depth:
  value: 7
min_child_weight:
  value: 4
n_estimators:
  value: 327
reg_alpha:
  value: 7
reg_lambda:
  value: 7
scaler:
  value: robust
variance_threshold:
  value: 0.024291883753154567
