wandb_version: 1

gamma:
  value: 4.5681614522176845
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 4
learning_rate:
  value: 0.009491995594977156
max_depth:
  value: 7
min_child_weight:
  value: 10
n_estimators:
  value: 206
reg_alpha:
  value: 5
reg_lambda:
  value: 6
scaler:
  value: robust
variance_threshold:
  value: 0.06131743975874065
