wandb_version: 1

gamma:
  value: 0.9277252978249576
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 3
learning_rate:
  value: 0.0003508791099619919
max_depth:
  value: 9
min_child_weight:
  value: 9
n_estimators:
  value: 315
reg_alpha:
  value: 4
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.09282107214966982
