wandb_version: 1

gamma:
  value: 3.491312953048266
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 14
learning_rate:
  value: 0.003567315038117584
max_depth:
  value: 7
min_child_weight:
  value: 11
n_estimators:
  value: 337
reg_alpha:
  value: 5
reg_lambda:
  value: 5
scaler:
  value: standard
variance_threshold:
  value: 0.041302075076960015
