wandb_version: 1

gamma:
  value: 0.7854308496846863
imputer:
  value: simple
imputer_strategy:
  value: median
knn_imputer_k:
  value: 13
learning_rate:
  value: 0.0030406320452879393
max_depth:
  value: 10
min_child_weight:
  value: 8
n_estimators:
  value: 398
reg_alpha:
  value: 7
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.09362411126622108
