wandb_version: 1

gamma:
  value: 0.5139019268029043
imputer:
  value: knn
imputer_strategy:
  value: median
knn_imputer_k:
  value: 5
learning_rate:
  value: 0.007914154617976428
max_depth:
  value: 9
min_child_weight:
  value: 6
n_estimators:
  value: 322
reg_alpha:
  value: 5
reg_lambda:
  value: 4
scaler:
  value: standard
variance_threshold:
  value: 0.05385644352035427
