wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711586557.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.10.9
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 4.450847887215298
imputer:
  desc: null
  value: simple
imputer_strategy:
  desc: null
  value: median
knn_imputer_k:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.009304724931550688
max_depth:
  desc: null
  value: 10
min_child_weight:
  desc: null
  value: 6
n_estimators:
  desc: null
  value: 473
reg_alpha:
  desc: null
  value: 6
reg_lambda:
  desc: null
  value: 4
scaler:
  desc: null
  value: standard
variance_threshold:
  desc: null
  value: 0.04813700003294763
